routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/questionares', 'QuestionareController@index');
Route::get('/create-questionair', 'QuestionareController@create');
Route::post('/create-questionair', 'QuestionareController@store');
Route::get('/edit-questionare/{questionare_id}', 'QuestionareController@edit');
Route::post('/edit-questionare/{questionare_id}', 'QuestionareController@update');
Route::delete('/delete-questionare/{questionare_id}', 'QuestionareController@destroy');
Route::get('/add-questions/{questionare_id}', 'QuestionareController@viewQuestions');
Route::post('/update-questions-answers', 'QuestionareController@updateQuestionsAnswers');

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $table = 'answer';

    public function question()
    {
        return $this->belongsTo('App\Models\Question');
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $table = 'question';

    public function questionare()
    {
        return $this->belongsTo('App\Models\Questionare');
    }


    public function answers()
    {
        return $this->hasMany('App\Models\Answer');
    }
}

app/Models/Questionare.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Questionare extends Model
{
    protected $table = 'questionare';

    public function questions()
    {
        return $this->hasMany('App\Models\Question');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/QuestionareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Questionare;
use App\Models\Question;
use App\Models\Answer;
use Auth;

class QuestionareController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questionares = Questionare::withCount('questions')->get();
        return view('questionare.listing')->with('questionares',$questionares);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questionare.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'        => 'required|string',
            'duration'    => 'required|numeric',
        ]);

        if($request->is_resumable=='yes') {
            $resumable = true;
        }
        else {
            $resumable = false;
        }
        $user_id =  Auth::id();

        $questionare = new Questionare;
        $questionare->name = $request->name;
        $questionare->duration = $request->duration;
        $questionare->unit = $request->unit;
        $questionare->is_resumable = $resumable;
        $questionare->is_published = true;
        $questionare->publisher_id = $user_id;
        $questionare->save();
        return redirect('/questionares')->with('status', 'New Questionare Created'); 
    }

    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $questionare = Questionare::findorfail($id);
        return view('questionare.edit')->with('questionare',$questionare);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $this->validate($request, [
            'name'        => 'required|string',
            'duration'    => 'required|numeric',
        ]);

        if($request->is_resumable=='yes') {
            $resumable = true;
        }
        else {
            $resumable = false;
        }

        $questionare = Questionare::findorfail($id);
        $questionare->name = $request->name;
        $questionare->duration = $request->duration;
        $questionare->unit = $request->unit;
        $questionare->is_resumable = $resumable;
        $questionare->save();
        return redirect('/questionares')->with('status', 'Questionare updated!'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $questionare = Questionare::findorfail($id);
        $questionare->delete();
        return redirect('/questionares')->with('status', 'Questionare Deleted!'); 
    }


    public function viewQuestions($id) {
        $questions_with_answers = Question::with('answers')->where('questionare_id', '=', $id)->get();
        return view('questionare.view-questions')->with('questions_with_answers',$questions_with_answers)->with('questionare_id', $id);
    }

    public function updateQuestionsAnswers(Request $request) {
        $input_arr = $request->input_arr;
        $questionare = Questionare::findorfail($request->q_id);
        $questionare->questions()->delete();

        foreach ($input_arr as $q_arr) {
            $question = new Question();
            $question->q_text = $q_arr['q_txt'];
            $question->q_type = $q_arr['q_type'];
            $questionare->questions()->save($question);

            foreach ($q_arr['answers'] as $ans_obj) {
                $answer = new Answer();
                $answer->a_text = $ans_obj['answer_txt'];
                $answer->is_correct = $ans_obj['is_correct'];
                $question->answers()->save($answer);
            }
        }
        echo true;
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{asset('/css/app.css')}}" rel="stylesheet">
    

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li>
                                <a href="{{url('/home')}}">Home</a>
                            </li>
                            <li>
                                <a href="{{url('/questionares')}}">Questionares</a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{asset('/js/app.js')}}"></script>
    <script src="{{asset('/js/my-scripts.js')}}"></script>

</body>
</html>

resources/views/questionare/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h4>Create New Questionair</h4></div>

                <div class="panel-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form id="create-questionare-form" method="POST">
                        {{ csrf_field() }}
                      <div class="form-group">
                        <label>Questionair Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Enter Questionair Name" value="{{ old('name') }}" required>
                      </div>
                      <label>Duration</label>
                      <div class="form-group row">
                        <div class="col-md-12">
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="duration" id="duration" placeholder="Enter Duration" value="{{ old('duration') }}" required>
                            </div>
                            <div class="col-md-4">
                                <select class="form-control" name="unit" id="unit" required>
                                    <option value="min">Minutes</option>
                                    <option value="hr">Hours</option>
                                </select>
                            </div>
                        </div>
                      </div>
                      <div class="form-group">
                        Can Resume ?
                        <label class="radio-inline">
                            <input type="radio" name="is_resumable" value="yes" required> Yes
                        </label>
                        <label class="radio-inline">
                          <input type="radio" name="is_resumable" value="no" required> No
                        </label>
                      </div>
                      <button type="submit" class="btn btn-default">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questionare/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h4>Edit Questionair</h4></div>

                <div class="panel-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form id="edit-questionare-form" method="POST">
                        {{ csrf_field() }}
                      <div class="form-group">
                        <label>Questionair Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Enter Questionair Name" value="{{$questionare->name}}" required>
                      </div>
                      <label>Duration</label>
                      <div class="form-group row">
                        <div class="col-md-12">
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="duration" id="duration" placeholder="Enter Duration" value="{{$questionare->duration}}" required>
                            </div>
                            <div class="col-md-4">
                                <select class="form-control" name="unit" id="unit" required>
                                    @if($questionare->unit=='hr')
                                        <option value="hr" selected>Hours</option>
                                        <option value="min">Minutes</option>
                                    @else
                                        <option value="hr">Hours</option>
                                        <option value="min" selected>Minutes</option>
                                    @endif

                                </select>
                            </div>
                        </div>
                      </div>
                      <div class="form-group">
                        Can Resume ?
                        @if($questionare->is_resumable==true)
                            <label class="radio-inline">
                                <input type="radio" name="is_resumable" value="yes" required checked> Yes
                            </label>
                            <label class="radio-inline">
                              <input type="radio" name="is_resumable" value="no" required> No
                            </label>
                        @else
                            <label class="radio-inline">
                                <input type="radio" name="is_resumable" value="yes" required checked> Yes
                            </label>
                            <label class="radio-inline">
                              <input type="radio" name="is_resumable" value="no" required checked> No
                            </label>
                        @endif
                      </div>
                      <button type="submit" class="btn btn-default">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questionare/listing.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Questionairs</h3></div>

                <div class="panel-body">

                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a href="{{url('/create-questionair')}}">Create New</a><br><br>
                    <table id="listing-table" class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Number of Questions</th>
                                <th>Duration</th>
                                <th>Resumeable</th>
                                <th>Published</th>
                                <th>Edit Action</th>
                                <th>Delete Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i=1;?>
                            @foreach($questionares as $questionare)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{$questionare->name}}</td>
                                    <td>{{$questionare->questions_count}} | <a href="{{url('/add-questions/'.$questionare->id)}}">Add</a></td>
                                    <td>{{$questionare->duration}}{{$questionare->unit}}</td>
                                    <td>
                                        @if($questionare->is_resumable==true)
                                        Yes
                                        @else
                                        No
                                        @endif
                                    </td>
                                    <td>
                                        @if($questionare->is_published==true)
                                        Yes
                                        @else
                                        No
                                        @endif
                                    </td>
                                    <td><a href="{{url('/edit-questionare/'.$questionare->id)}}">Edit</a></td>
                                    <td>
                                    <form method="POST" id="delete-questionare-form" action="{{url('/delete-questionare/'.$questionare->id)}}">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="dlt-btn btn btn-link">Delete</button>
                                    </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questionare/view-questions.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Add Questions</h3></div>

                <div class="panel-body">
                    <div class="alert alert-success hidden">
                      <strong>Success!</strong> Questions Updated
                    </div>
                    <input type="hidden" id="questionare-id" value="{{$questionare_id}}">
                    @php $i = 1;@endphp
                    @foreach($questions_with_answers as $question)
                        @php
                        $answers = $question->answers;
                        @endphp
                        <div class="single-question">
                            <div class="form-group question-type-div">
                                <label>Question Type</label>
                                <select class="question-type form-control" style="width:270px;">
                                        <option value="">Select Type</option>
                                    @if($question->q_type==1)
                                        <option value="1" selected>Short Answer</option>
                                        <option value="2">Multiple Choice (Single Option)</option>
                                        <option value="3">Multiple Choice (Multiple Options)</option>
                                    @elseif($question->q_type==2)
                                        <option value="1">Short Answer</option>
                                        <option value="2" Selected>Multiple Choice (Single Option)</option>
                                        <option value="3">Multiple Choice (Multiple Options)</option>
                                    @else
                                        <option value="1">Short Answer</option>
                                        <option value="2">Multiple Choice (Single Option)</option>
                                        <option value="3" Selected>Multiple Choice (Multiple Options)</option>
                                    @endif
                                </select>
                            </div>
                            
                            <div class="row form-group question-div">
                                <div class="col-sm-12 col-md-12">
                                    <div class="col-md-8 col-sm-8">
                                    <label>Question</label>
                                        <input type="text" name="question-text" placeholder="Enter Question" class="question-text form-control" value="{{$question->q_text}}">
                                    </div>
                                    <div class="col-sm-4 col-md-4">
                                        <br>
                                        <a href="#" class="dlt-question">Delete Question</a>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group answer-div">
                                @if($question->q_type==1)
                                    @foreach($answers as $answer)
                                        <div class="ans-div">
                                          <label>Answer</label>
                                          <input type="text" name="txt-ans" class="txt-ans form-control" style="width:470px" value="{{$answer->a_text}}">  
                                        </div>
                                        
                                    @endforeach
                                @elseif($question->q_type==2)
                                    <div class="ans-div">
                                        @foreach($answers as $answer)
                                            <div class="row my-ans-div">
                                                <div class="col-sm-12 col-md-12">
                                                    <div class="col-sm-5 col-md-5">
                                                        <label>Choice</label>
                                                        <input type="text" name="" class="form-control txt-ans" value="{{$answer->a_text}}">
                                                    </div>
                                                    <div class="col-md-2 col-sm-2">
                                                        <label style="margin-top:10px">Correct ?</label>
                                                    </div>
                                                    <div class="col-sm-2 col-md-2">
                                                         
                                                        @if($answer->is_correct==1)
                                                            <input type="radio" name="is-correct-{{$i}}" class="form-control is-correct" checked>
                                                        @else
                                                            <input type="radio" name="is-correct-{{$i}}" class="form-control is-correct">
                                                        @endif

                                                    </div>
                                                    <div class="col-sm-3 col-md-3">
                                                        <br>
                                                        <a href="#" class="remove-choice-btn">Remove Choice</a>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                        @endforeach
                                        <div class="radio-appender"></div>
                                        <a href="#" class="add-choice-radio-btn">Add Choice</a>
                                    </div>
                                @else
                                    <div class="ans-div">
                                        @foreach($answers as $answer)
                                            <div class="row my-ans-div">
                                                <div class="col-sm-12 col-md-12">
                                                    <div class="col-sm-5 col-md-5">
                                                        <label>Choice</label>
                                                        <input type="text" name="" class="form-control txt-ans" value="{{$answer->a_text}}">
                                                    </div>
                                                    <div class="col-md-2 col-sm-2">
                                                        <label style="margin-top:10px">Correct ?</label>
                                                    </div>
                                                    <div class="col-sm-2 col-md-2">
                                                         
                                                        @if($answer->is_correct==1)
                                                            <input type="checkbox" name="is-correct-{{$i}}" class="form-control is-correct" checked>
                                                        @else
                                                            <input type="checkbox" name="is-correct-{{$i}}" class="form-control is-correct">
                                                        @endif

                                                    </div>
                                                    <div class="col-sm-3 col-md-3">
                                                        <br>
                                                        <a href="#" class="remove-choice-btn">Remove Choice</a>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                        @endforeach
                                        <div class="check-appender"></div>
                                        <a href="#" class="add-choice-check-btn">Add Choice</a>
                                    </div>
                                @endif
                                
                            </div>
                            <hr>
                        </div>
                        @php $i++; @endphp
                    @endforeach
                    <div class="question-appender"></div>
                    <a href="#" class="add-question">Add new Question</a><br><br>
                    <button class="btn btn-primary update-all">Update</button>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection